const mongoose = require('mongoose');

const UnionOutmigrationSchema = mongoose.Schema({
  'User ID': { type: String },
  'Submitted By': { type: String },
  Date: { type: Date },
  Time: { type: String },
  'Trap Operating': { type: String },
  RPM: { type: Number },
  Debris: { type: String },
  Visibility: { type: String },
  Flow: { type: String },
  'Water Temp': { type: Number },
  'Hobo Temp': { type: Number },
  'Chum Fry': { type: Number },
  'Chum Fry Mort': { type: Number },
  'Chum DNA Taken': { type: Number },
  'Chum DNA IDs': { type: String },
  'Chum Marked': { type: Number },
  'Chum Marked Mort': { type: Number },
  'Chum Recap': { type: Number },
  'Chum Recap Mort': { type: Number },
  'Coho Fry': { type: Number },
  'Coho Fry Mort': { type: Number },
  'Coho Parr': { type: Number },
  'Coho Parr Mort': { type: Number },
  'Coho Smolt': { type: Number },
  'Coho Smolt Mort': { type: Number },
  'Coho Smolt Marked': { type: Number },
  'Coho Smolt Marked Mort': { type: Number },
  'Coho Smolt Recap': { type: Number },
  'Coho Smolt Recap Mort': { type: Number },
  Steelhead: { type: Number },
  'Steelhead Mort': { type: Number },
  'Steelhead Marked': { type: Number },
  'Steelhead Marked Mort': { type: Number },
  'Steelhead Recap': { type: Number },
  'Steelhead Recap Mort': { type: Number },
  Cutthroat: { type: Number },
  'Cutthroat Mort': { type: Number },
  Chinook: { type: Number },
  'Chinook Mort': { type: Number },
  Sculpin: { type: Number },
  'Sculpin Mort': { type: Number },
  Lamprey: { type: Number },
  'Lamprey Mort': { type: Number },
  Comments: { type: String },
  'Created At': { type: Date, default: Date.now },
  // Legacy fields (historical data only, not used in new entries)
  // 'Marked Chum Released': { type: Int32 },
  // Stickleback: { type: Int32 },
  // 'Pink Fry': { type: Int32 },
});

module.exports = mongoose.model(
  'UnionOutmigration',
  UnionOutmigrationSchema,
  'Union_Outmigration',
);
