const mongoose = require('mongoose');

const UnionOutmigrationSchema = mongoose.Schema({
  date: { type: Date },
  time: { type: String },
  trapOperating: { type: String },
  rpm: { type: Number },
  debris: { type: String },
  waterTemp: { type: Number },
  hoboTemp: { type: Number },
  visibility: { type: String },
  flow: { type: String },
  chumCaught: { type: Number },
  chumDnaTaken: { type: Number },
  chumMarked: { type: Number },
  chumMarkedRecap: { type: Number },
  chumMorts: { type: Number },
  chumDnaIds: { type: String },
  chumMortsMarked: { type: Number },
  chumMortsRecap: { type: Number },
  cohoFryCaught: { type: Number },
  cohoSmoltCaught: { type: Number },
  cohoSmoltMarked: { type: Number },
  cohoSmoltMarkedRecap: { type: Number },
  cohoFryMorts: { type: Number },
  cohoSmoltMorts: { type: Number },
  cohoSmoltMortsMarked: { type: Number },
  cohoSmoltMortsRecap: { type: Number },
  cohoParrCaught: { type: Number },
  steelheadCaught: { type: Number },
  steelheadMarked: { type: Number },
  steelheadMarkedRecap: { type: Number },
  cohoParrMorts: { type: Number },
  steelheadMorts: { type: Number },
  steelheadMortsMarked: { type: Number },
  steelheadMortsRecap: { type: Number },
  cutthroatCaught: { type: Number },
  chinookCaught: { type: Number },
  sculpinCaught: { type: Number },
  lampreyCaught: { type: Number },
  cutthroatMorts: { type: Number },
  chinookMorts: { type: Number },
  sculpinMorts: { type: Number },
  lampreyMorts: { type: Number },
  comments: { type: String },
});

module.exports = mongoose.model(
  'UnionOutmigration',
  UnionOutmigrationSchema,
  'Union_Outmigration',
);
